// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooloskiVrt.Data;

#nullable disable

namespace ZooloskiVrt.Migrations
{
    [DbContext(typeof(ZooloskiVrtContext))]
    [Migration("20260122181819_InitialSeed")]
    partial class InitialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZooloskiVrt.Models.Bolovanje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Kraj")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Pocetak")
                        .HasColumnType("datetime2");

                    b.Property<int>("RadnikID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RadnikID");

                    b.ToTable("Bolovanja");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.GodisnjiOdmor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Kraj")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Pocetak")
                        .HasColumnType("datetime2");

                    b.Property<int>("RadnikID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RadnikID");

                    b.ToTable("GodisnjiOdmori");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Incident", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ozbiljnost")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Incidenti");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.IncidentNastamba", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("IncidentID")
                        .HasColumnType("int");

                    b.Property<int>("NastambaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IncidentID");

                    b.HasIndex("NastambaID");

                    b.ToTable("IncidentNastambe");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.IncidentZivotinja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("IncidentID")
                        .HasColumnType("int");

                    b.Property<int>("ZivotinjaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IncidentID");

                    b.HasIndex("ZivotinjaID");

                    b.ToTable("IncidentZivotinje");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Licenca", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DatumIsteka")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RadnikID")
                        .HasColumnType("int");

                    b.Property<bool>("Trajna")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("RadnikID");

                    b.ToTable("Licence");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Nastamba", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazinaOsuncanosti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Nastambe");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Obaveza", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("NastambaID")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RadnikID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("NastambaID");

                    b.HasIndex("RadnikID");

                    b.ToTable("Obaveze");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Obuka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RadnikID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RadnikID");

                    b.ToTable("Obuke");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Posjetitelj", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ImeGrupe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TerminPosjete")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VodicID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VodicID");

                    b.ToTable("Posjetitelji");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Radnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kontakt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obrazovanje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Radnici");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Sanacija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("IncidentID")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RadnikID")
                        .HasColumnType("int");

                    b.Property<decimal>("Trosak")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("IncidentID");

                    b.HasIndex("RadnikID");

                    b.ToTable("Sanacije");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Smjena", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Kraj")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Pocetak")
                        .HasColumnType("datetime2");

                    b.Property<int>("RadnikID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RadnikID");

                    b.ToTable("Smjene");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Trosak", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Vrsta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZivotinjaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ZivotinjaID");

                    b.ToTable("Troskovi");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Zivotinja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Aktivna")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumNabave")
                        .HasColumnType("datetime2");

                    b.Property<string>("HrvatskiNaziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatinskiNaziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NacinNabave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NastambaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NastambaID");

                    b.ToTable("Zivotinje");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Bolovanje", b =>
                {
                    b.HasOne("ZooloskiVrt.Models.Radnik", "Radnik")
                        .WithMany("Bolovanja")
                        .HasForeignKey("RadnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Radnik");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.GodisnjiOdmor", b =>
                {
                    b.HasOne("ZooloskiVrt.Models.Radnik", "Radnik")
                        .WithMany("GodisnjiOdmori")
                        .HasForeignKey("RadnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Radnik");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.IncidentNastamba", b =>
                {
                    b.HasOne("ZooloskiVrt.Models.Incident", "Incident")
                        .WithMany("IncidentiNastambe")
                        .HasForeignKey("IncidentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooloskiVrt.Models.Nastamba", "Nastamba")
                        .WithMany("IncidentiNastambe")
                        .HasForeignKey("NastambaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("Nastamba");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.IncidentZivotinja", b =>
                {
                    b.HasOne("ZooloskiVrt.Models.Incident", "Incident")
                        .WithMany("IncidentiZivotinje")
                        .HasForeignKey("IncidentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooloskiVrt.Models.Zivotinja", "Zivotinja")
                        .WithMany("IncidentiZivotinje")
                        .HasForeignKey("ZivotinjaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("Zivotinja");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Licenca", b =>
                {
                    b.HasOne("ZooloskiVrt.Models.Radnik", "Radnik")
                        .WithMany("Licence")
                        .HasForeignKey("RadnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Radnik");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Obaveza", b =>
                {
                    b.HasOne("ZooloskiVrt.Models.Nastamba", "Nastamba")
                        .WithMany("Obaveze")
                        .HasForeignKey("NastambaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooloskiVrt.Models.Radnik", "Radnik")
                        .WithMany("Obaveze")
                        .HasForeignKey("RadnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nastamba");

                    b.Navigation("Radnik");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Obuka", b =>
                {
                    b.HasOne("ZooloskiVrt.Models.Radnik", "Radnik")
                        .WithMany("Obuke")
                        .HasForeignKey("RadnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Radnik");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Posjetitelj", b =>
                {
                    b.HasOne("ZooloskiVrt.Models.Radnik", "Vodic")
                        .WithMany()
                        .HasForeignKey("VodicID");

                    b.Navigation("Vodic");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Sanacija", b =>
                {
                    b.HasOne("ZooloskiVrt.Models.Incident", "Incident")
                        .WithMany("Sanacije")
                        .HasForeignKey("IncidentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooloskiVrt.Models.Radnik", "Radnik")
                        .WithMany("Sanacije")
                        .HasForeignKey("RadnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("Radnik");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Smjena", b =>
                {
                    b.HasOne("ZooloskiVrt.Models.Radnik", "Radnik")
                        .WithMany("Smjene")
                        .HasForeignKey("RadnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Radnik");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Trosak", b =>
                {
                    b.HasOne("ZooloskiVrt.Models.Zivotinja", "Zivotinja")
                        .WithMany("Troskovi")
                        .HasForeignKey("ZivotinjaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zivotinja");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Zivotinja", b =>
                {
                    b.HasOne("ZooloskiVrt.Models.Nastamba", "Nastamba")
                        .WithMany("Zivotinje")
                        .HasForeignKey("NastambaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nastamba");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Incident", b =>
                {
                    b.Navigation("IncidentiNastambe");

                    b.Navigation("IncidentiZivotinje");

                    b.Navigation("Sanacije");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Nastamba", b =>
                {
                    b.Navigation("IncidentiNastambe");

                    b.Navigation("Obaveze");

                    b.Navigation("Zivotinje");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Radnik", b =>
                {
                    b.Navigation("Bolovanja");

                    b.Navigation("GodisnjiOdmori");

                    b.Navigation("Licence");

                    b.Navigation("Obaveze");

                    b.Navigation("Obuke");

                    b.Navigation("Sanacije");

                    b.Navigation("Smjene");
                });

            modelBuilder.Entity("ZooloskiVrt.Models.Zivotinja", b =>
                {
                    b.Navigation("IncidentiZivotinje");

                    b.Navigation("Troskovi");
                });
#pragma warning restore 612, 618
        }
    }
}
